apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # 在 ExternalSecret 之前建立
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"

      # Kubernetes Auth Method
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"

          # ServiceAccount Token 路徑
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
