# Patch to force Tempo deployment to app-worker and use topolvm storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: all
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/workload-apps: "true"
  volumeClaimTemplates:
    - metadata:
        name: tempo-data
      spec:
        storageClassName: topolvm-provisioner
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
