apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server

spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
