apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
      data:
        # TLS certificates
        tls.crt: "{{ .tls_crt | toString }}"
        tls.key: "{{ .tls_key | toString }}"

        # Admin password
        admin.password: "{{ .admin_password | toString }}"
        admin.passwordMtime: "{{ .admin_password_mtime | toString }}"

        # Server signature key
        server.secretkey: "{{ .server_secretkey | toString }}"

        # GitHub SSO
        dex.github.clientSecret: "{{ .github_client_secret | toString }}"

        # Webhook
        webhook.github.secret: "{{ .github_webhook_secret | toString }}"
  data:
  - secretKey: tls_crt
    remoteRef:
      key: secret/infrastructure/argocd
      property: tls-crt
  - secretKey: tls_key
    remoteRef:
      key: secret/infrastructure/argocd
      property: tls-key
  - secretKey: admin_password
    remoteRef:
      key: secret/infrastructure/argocd
      property: admin-password
  - secretKey: admin_password_mtime
    remoteRef:
      key: secret/infrastructure/argocd
      property: admin-password-mtime
  - secretKey: server_secretkey
    remoteRef:
      key: secret/infrastructure/argocd
      property: server-secretkey
  - secretKey: github_client_secret
    remoteRef:
      key: secret/infrastructure/argocd
      property: github-client-secret
  - secretKey: github_webhook_secret
    remoteRef:
      key: secret/infrastructure/argocd
      property: github-webhook-secret
