apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: detectviz-quota
    namespace: detectviz
  spec:
    hard:
      requests.cpu: "20"
      requests.memory: 40Gi
      limits.cpu: "40"
      limits.memory: 80Gi
      persistentvolumeclaims: "20"
      pods: "50"
      services: "20"
      secrets: "50"
      configmaps: "50"
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: monitoring-quota
    namespace: monitoring
  spec:
    hard:
      requests.cpu: "8"
      requests.memory: 16Gi
      limits.cpu: "16"
      limits.memory: 32Gi
      persistentvolumeclaims: "10"
      pods: "30"
      services: "10"
      secrets: "20"
      configmaps: "20"
