---
# Vault 備份 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backup-pvc
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-backup
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/managed-by: gitops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topolvm-provisioner
  resources:
    requests:
      storage: 20Gi  # 備份檔案儲存空間

---
# Vault 備份 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-backup
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-backup
    app.kubernetes.io/part-of: vault

---
# Vault 備份 Role（授予 snapshot 權限）
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-backup
  namespace: vault
spec:
  rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
# Vault 備份 RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-backup
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-backup
subjects:
- kind: ServiceAccount
  name: vault-backup
  namespace: vault

---
# Vault 自動備份 CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-backup
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # 在 Vault 部署後執行
spec:
  schedule: "0 2 * * *"  # 每天凌晨 2 點執行
  successfulJobsHistoryLimit: 7  # 保留最近 7 次成功的備份記錄
  failedJobsHistoryLimit: 3  # 保留最近 3 次失敗的備份記錄
  concurrencyPolicy: Forbid  # 禁止並發執行
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Job 完成後 24 小時自動清理
      template:
        metadata:
          labels:
            app.kubernetes.io/name: vault-backup
            app.kubernetes.io/part-of: vault
        spec:
          serviceAccountName: vault-backup
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: backup
            image: hashicorp/vault:1.15.6
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "[$(date)] Starting Vault backup..."

              # 設定 Vault 地址
              export VAULT_ADDR="http://vault-0.vault-internal:8200"
              export VAULT_SKIP_VERIFY=true

              # 檢查 Vault 狀態
              if ! vault status > /dev/null 2>&1; then
                echo "[$(date)] ERROR: Vault is sealed or unreachable"
                exit 1
              fi

              # 生成備份檔案名稱（帶時間戳）
              BACKUP_FILE="/backup/vault-snapshot-$(date +%Y%m%d-%H%M%S).snap"

              # 執行 Raft snapshot
              echo "[$(date)] Creating snapshot: $BACKUP_FILE"
              vault operator raft snapshot save "$BACKUP_FILE"

              # 驗證備份檔案
              if [ -f "$BACKUP_FILE" ]; then
                FILE_SIZE=$(stat -f%z "$BACKUP_FILE" 2>/dev/null || stat -c%s "$BACKUP_FILE")
                echo "[$(date)] ✅ Backup completed successfully"
                echo "[$(date)] Backup file: $BACKUP_FILE"
                echo "[$(date)] File size: $FILE_SIZE bytes"
              else
                echo "[$(date)] ❌ Backup file not found"
                exit 1
              fi

              # 清理超過 30 天的舊備份
              echo "[$(date)] Cleaning up old backups (> 30 days)..."
              find /backup -name "vault-snapshot-*.snap" -type f -mtime +30 -delete

              # 列出當前所有備份
              echo "[$(date)] Current backups:"
              ls -lh /backup/vault-snapshot-*.snap 2>/dev/null || echo "No backups found"

              echo "[$(date)] Backup process completed"
            env:
            - name: VAULT_ADDR
              value: "http://vault-0.vault-internal:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            volumeMounts:
            - name: backup
              mountPath: /backup
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: false  # Vault CLI 需要寫入臨時檔案
              runAsNonRoot: true
              runAsUser: 100
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: vault-backup-pvc
