# ApplicationSet for Application Layer
# 使用 List Generator 明確定義每個應用的 namespace mapping
# syncPolicy 設為手動 ({}), 以建立 Vault 初始化的「手動閘門」
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Platform Services (獨立 namespace)
          - name: postgresql
            path: argocd/apps/observability/postgresql/overlays
            namespace: postgresql
            category: platform-service

          - name: keycloak
            path: argocd/apps/identity/keycloak/overlays
            namespace: keycloak
            category: platform-service

          # Application Layer (獨立 namespace)
          - name: grafana
            path: argocd/apps/observability/grafana/overlays
            namespace: grafana
            category: application

          # Observability Backend (統一 monitoring namespace)
          - name: prometheus
            path: argocd/apps/observability/prometheus/overlays
            namespace: monitoring
            category: observability

          - name: loki
            path: argocd/apps/observability/loki/overlays
            namespace: monitoring
            category: observability

          - name: tempo
            path: argocd/apps/observability/tempo/overlays
            namespace: monitoring
            category: observability

          - name: mimir
            path: argocd/apps/observability/mimir/overlays
            namespace: monitoring
            category: observability

          - name: minio
            path: argocd/apps/observability/minio/overlays
            namespace: monitoring
            category: observability

          - name: alertmanager
            path: argocd/apps/observability/alertmanager/overlays
            namespace: monitoring
            category: observability

          - name: alloy
            path: argocd/apps/observability/alloy/overlays
            namespace: monitoring
            category: observability

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/category: "{{category}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "{{path}}"
    spec:
      project: default
      source:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true # 仍維持手動同步，但強制 Argo CD 先建立 namespace
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: "*"
          jsonPointers:
            - /data
