# ApplicationSet for Application Layer
# 使用 List Generator 明確定義每個應用的 namespace mapping
# syncPolicy 設為手動 ({}), 以建立 Vault 初始化的「手動閘門」
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Platform Services (獨立 namespace) - Project: detectviz
          - name: postgresql
            path: argocd/apps/observability/postgresql/overlays/production
            namespace: postgresql
            project: detectviz
            category: platform-service
            syncWave: "1"

          - name: keycloak
            path: argocd/apps/identity/keycloak/overlays/production
            namespace: keycloak
            project: detectviz
            category: platform-service
            syncWave: "2"

          - name: pgbouncer-hpa
            path: argocd/apps/observability/pgbouncer-hpa/overlays/production
            namespace: postgresql
            project: detectviz
            category: platform-service
            syncWave: "2"

          # Observability Backend (統一 monitoring namespace) - Project: platform-observability
          - name: minio
            path: argocd/apps/observability/minio/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "1"

          - name: mimir
            path: argocd/apps/observability/mimir/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "2"

          - name: prometheus
            path: argocd/apps/observability/prometheus/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "3"

          - name: loki
            path: argocd/apps/observability/loki/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "3"

          - name: tempo
            path: argocd/apps/observability/tempo/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "3"

          - name: alertmanager
            path: argocd/apps/observability/alertmanager/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "3"

          - name: alloy
            path: argocd/apps/observability/alloy/overlays/production
            namespace: monitoring
            project: platform-observability
            category: observability
            syncWave: "4"

          # Application Layer (獨立 namespace) - Project: detectviz
          - name: grafana
            path: argocd/apps/observability/grafana/overlays/production
            namespace: grafana
            project: detectviz
            category: application
            syncWave: "5"
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/category: "{{category}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "{{path}}"
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: "{{project}}"
      source:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true # 仍維持手動同步，但強制 Argo CD 先建立 namespace
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: "*"
          jsonPointers:
            - /data
