# ApplicationSet for P5 applications
# 使用 Git Generator 偵測 argocd/apps/observability/* 和 argocd/apps/identity/*。
# syncPolicy 必須是 syncPolicy: {} (手動)，以建立 Vault 初始化的「手動閘門」。
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        revision: HEAD
        directories:
          - path: argocd/apps/observability/*
          - path: argocd/apps/identity/*
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy: {} # 手動同步
