# ApplicationSet for P4 infrastructure applications
# 使用 Git Generator 偵測 argocd/apps/infrastructure/*。
# syncPolicy 必須是 automated。
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        revision: HEAD
        directories:
          - path: argocd/apps/infrastructure/*
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "git@github.com:detectviz/detectviz-gitops.git"
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated: # 自動同步
          prune: true
          selfHeal: true
        syncOptions: # 建立命名空間
          - CreateNamespace=true
