# ExternalSecret to fetch DB credentials from Vault for Keycloak
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-db-creds
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/keycloak
        property: POSTGRES_PASSWORD
