# Patch to add tolerations to grafana-alloy DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-alloy
spec:
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
