# Root Argo CD Application
# This is the entry point for the entire GitOps structure.
# It manages all ApplicationSets.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:detectviz/detectviz-gitops.git'
    path: argocd/appsets
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
