---
# Root ArgoCD Application - 管理所有 ApplicationSets
# 這是整個 GitOps 架構的入口點,負責載入所有環境的 ApplicationSets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # 最高優先級
spec:
  project: platform-bootstrap

  source:
    repoURL: git@github.com:detectviz/detectviz-gitops.git
    targetRevision: main
    path: appsets # 指向所有 ApplicationSet 清單

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false # argocd 命名空間已存在
      - ServerSideApply=true
