apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cert-manager
  name: cert-manager-webhook
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
