# Patch to deploy Loki to app-worker node and use topolvm
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/workload-apps: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        storageClassName: topolvm-provisioner
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
