# PgBouncer - PostgreSQL 連線池 (Connection Pooler) 的水平 Pod 自動擴展 (HPA)
#
# 本 HPA 旨在根據 CPU 使用率，自動調整 PgBouncer 的副本數，以應對變動的資料庫連線負載。
# PgBouncer 作為一個無狀態的代理層，非常適合使用 HPA 進行水平擴展。
#
# **注意**: 此 HPA 僅適用於 PgBouncer Deployment，不適用於 PostgreSQL StatefulSet 本身。
#
# 參考文件:
# - HPA 官方文檔: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pgbouncer-hpa
  namespace: detectviz # PgBouncer 部署所在的命名空間。
  labels:
    app: pgbouncer
    layer: data
    app.kubernetes.io/managed-by: argocd # 表明此資源由 ArgoCD 透過 GitOps 管理。
spec:
  # 'scaleTargetRef' 指定了 HPA 要監控與擴展的目標資源。
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer # 目標為 'pgbouncer' Deployment。

  # --- 擴展範圍 ---
  minReplicas: 3  # 最小副本數，即使在低負載時也維持至少 3 個實例以確保高可用。
  maxReplicas: 12 # 最大副本數，防止因負載瞬間飆高而無限制地創建 Pod。

  # --- 擴展指標 ---
  # HPA 將根據以下指標來決定是否需要擴展或縮減。
  metrics:
    - type: Resource # 我們使用基於資源的指標。
      resource:
        name: cpu # 監控的資源是 CPU。
        target:
          type: Utilization # 監控的目標類型是使用率百分比。
          # 當所有 Pod 的平均 CPU 使用率超過 60% 時，HPA 將觸發擴展。
          averageUtilization: 60

  # --- 擴展行為 ---
  # 'behavior' 區塊允許我們微調擴展與縮減的行為，以使其更平滑、更穩定。
  behavior:
    # 擴展 (Scale Up) 行為
    scaleUp:
      # 在做出擴展決策後，會等待 90 秒的穩定窗口，觀察指標是否持續超標，以防止因短暫的峰值而觸發不必要的擴展。
      stabilizationWindowSeconds: 90
      policies:
        # 在 30 秒的週期內，最多將當前副本數增加 50%。
        - type: Percent
          value: 50
          periodSeconds: 30

    # 縮減 (Scale Down) 行為
    scaleDown:
      # 在做出縮減決策後，會等待 300 秒 (5 分鐘) 的穩定窗口，確保負載確實已經下降，以防止 'flapping'。
      stabilizationWindowSeconds: 300
      policies:
        # 在 90 秒的週期內，最多只縮減 1 個 Pod。
        - type: Pods
          value: 1
          periodSeconds: 90
