# MetalLB IP Address Pool Configuration
# 修正 IP 範圍以避免與現有設備衝突
# 原始範圍 192.168.0.100-192.168.0.150 會與本機 (.101) 和 IPMI (.104) 衝突
# 新範圍 192.168.0.200-192.168.0.220 避免了這些衝突
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.200-192.168.0.220
