# ExternalSecret to fetch PostgreSQL credentials from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: detectviz-postgresql-admin
    creationPolicy: Owner
  data:
    # PostgreSQL superuser password
    - secretKey: postgres-password
      remoteRef:
        key: secret/data/postgresql/admin
        property: postgres-password

    # Application user password
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/admin
        property: app-password

    # Replication manager password
    - secretKey: repmgr-password
      remoteRef:
        key: secret/data/postgresql/admin
        property: repmgr-password

---
# ExternalSecret for Pgpool users
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgpool-users
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: detectviz-pgpool-users
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        pgpool_passwd: |
          {{ .postgresUser }}:{{ .postgresPasswordMd5 }}
          {{ .appUser }}:{{ .appPasswordMd5 }}
  dataFrom:
    - extract:
        key: secret/data/postgresql/admin

---
# ExternalSecret for PostgreSQL initialization scripts
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: detectviz-postgresql-initdb
    creationPolicy: Owner
  data:
    - secretKey: init-grafana.sql
      remoteRef:
        key: secret/data/postgresql/initdb
        property: init-grafana-sql
