# Patch to force PostgreSQL deployment to app-worker and use TopoLVM storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/workload-apps: "true"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: topolvm-provisioner
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
